### PR TITLE
added babel transpiling to es5

### PR DESCRIPTION
**Pull request by freeworlder**
without it building react-apps requiring this module ends with error 
`Unexpected token: name (Store) [./node_modules/idb-keyval/dist/idb-keyval.mjs:1,0]`
as es5 js doesn't support classes

### CODE REVIEW

**Comment by jakearchibald** [comment]
Thanks! However, I don't want to transpile all editions of the library as it increases the size.

In 96cbfebb612fbee6fa4a0149935c63ec27bb0c4e I added a compat version.

**Comment by freeworlder** [comment]
Hi! Yes, it does increase. But I am facing a problem when building a react app using the package returns error because the package isn't transpiled. What is an other way to deal with it besides having this library babelised?

**Comment by suprsidr** [comment]
@freeworlder see https://twitter.com/suprsidr/status/994367269290594305

**Comment by freeworlder** [comment]
Thank you! I believe I tried this, but will re-check. Thank you again
anyway)

**Comment by jakearchibald** [comment]
@freeworlder I've added a transpiled version. However, it's better to set up a transpiler as part of your project, since your transpilation requirements may differ to everyone else's.

**Pull request closed without merging**
