### PR TITLE
Implemented Edge support

### PR DESCRIPTION
**Pull request by rodgobbi**
Hey @jakearchibald, I tested my implementation on Edge and Chrome and it worked, but I want to share with you what I discovered, so you can review the code better and give a good feedback. Thus, this first implementation may be too fresh, but as I said, I want first to share my acquired knowledge, so then we can improve the code, then test on IE, and the others (I don't have access to a Safari to test on it).   
By the way, you prepared I really good test at the last test case.   
The Edge caveats:
1. If you call `indexedDB.open(dbName, version)`, and `version` is `undefined`, Edge throws an error. But calling as `indexedDB.open(dbName)` achieves the desired behavior.
2. Edge doesn't allow a version change of a given db if there is any connection to it, thus `onversionchange` is never called, instead the `blocked` event is fired on the upgrade request. And by the way, if an open request is blocked in a window, any other window trying to open the blocked db, even with the current version (or undefined version), just requesting to opening, gets "blocked", meaning that the open request stays pending until the blocking is released.   
To solve 2, I created an array to store all the created connections, thus when an upgraded is needed, the past connections related to the target db are refreshed. (BTW, could you give some feedback if it could happen of the refreshing being resolved before the upgrade? It's hard for me to visualize if there is any race condition)
But still there is a big BUT on Edge, if another window tries to upgrade a db which has connections open on another window, it gets blocked, so this implementation isn't entirely complete, any thoughts on any solution are welcome. I tested on Chrome and it doesn't face this problem, and the `onversionchange` is still there to handle this case across multiple windows.

### CODE REVIEW

**Comment by jakearchibald** [comment]
> If you call indexedDB.open(dbName, version), and version is undefined, Edge throws an error. But calling as indexedDB.open(dbName) achieves the desired behavior.

Hah, good to know!

> Edge doesn't allow a version change of a given db if there is any connection to it

That's correct according to the indexeddb spec https://w3c.github.io/IndexedDB/#handling-versionchange, but it should still fire the `versionchange` event (along with the `blocked` event).

> if an open request is blocked in a window, any other window trying to open the blocked db, even with the current version (or undefined version), just requesting to opening, gets "blocked", meaning that the open request stays pending until the blocking is released.

I *think* that's correct according to the spec.

> But still there is a big BUT on Edge, if another window tries to upgrade a db which has connections open on another window, it gets blocked, so this implementation isn't entirely complete

Seems like you've gotten stuck in the same place I did, except you've identified that the root is in Edge's handling of `versionchange`. A good step forward!

**Comment by rodgobbi** [comment]
I've tested again, I've put event handlers both for the open request (`openreq`) and for the resulting connection (`openreq.result`), events for: `versionchange`, `blocked`, `error`, `abort`, `close` and `upgradeneeded`, to try to react to any attempt to upgrade the version of the db and close the existing connection.   
Couldn't get anything on Edge, the only event triggered is the `blocked` on the failed open request, from which I can't access anything from the db, and even if it was possible, I think it won't be possible to close any existing connections.   
So, does it qualify a bug for this spec?   
> That's correct according to the indexeddb spec https://w3c.github.io/IndexedDB/#handling-versionchange, but it should still fire the versionchange event (along with the blocked event).  

And, any planned further steps?

**Comment by jakearchibald** [comment]
From: http://dexie.org/docs/Dexie/Dexie.on.blocked 

> IE, Edge and Safari does NOT implement the “versionchange” event, which could lead to that the blocked event occurred every time you didn’t properly close your db instance. But since Dexie v1.3.6, the “versionchange” event is “kind of” polyfilled for those browsers so that this doesnt happen anymore. “Kind of” because it’s only triggered for databases in the same window.

Seems we're not the first to run into this (I imagine this was written before Safari overhauled its IDB implementation).

**Comment by rodgobbi** [comment]
What a headache and frustrating limitation these browsers impose.   
Good to confirm this issue with previous experience from others.   
Even if Safari is correct nowadays, Edge and IE will still be broken.  
Now that a I think of it, the app that I'm implementing right now is prone to this bug.   
But definitely I'd use this new version of the lib if it was available at the time, we're tied to this problem on these browser in any case and with any lib.   
Your call to decide what to do. I'm glad to retribute the ease the lib gave me, and learn more on the process.  
But damn (I hope this word doesn't sound impolite to native english speakers), again, it feels frustrating.

**Comment by jakearchibald** [comment]
Totally share your frustration here. Will let it bounce around my head a bit, but if I can't solve it, I guess I'll have to remove the feature.

**Comment by jakearchibald** [comment]
I'm recommending https://github.com/jakearchibald/idb/ for folks that have more advanced use-cases.

**Pull request closed without merging**
