### PR TITLE
Add upsert function

### PR DESCRIPTION
**Pull request by compmeist**
In using this library, I found I needed this function, which I called "upsert".

### CODE REVIEW

**Comment by jakearchibald** [comment]
This seems pretty similar to `update`. Can you explain why it's needed?

**Comment by compmeist** [comment]
I see what you're saying.  (I am not immune to being incompetent.)  However, the extra parameter gets associated with the promise, does it not?   e.g. if I hold temperature for 'Chicago' in a key-val entry, and I hold temperature for 'New York' in an entry, and I want to increment by different degree values, how can I do this with update() ?

**Comment by jakearchibald** [comment]
Can you show me how you'd do that with your upsert function?

**Comment by compmeist** [comment]
Define the callback with extra param, e.g.
`var myTempUpdate = (v,vDelta) => (v || 0) + (vDelta || 1);`
and if the temperature difference is 3 for Chicago
`upsert('Chicago',myTempUpdate,3).then(()=>{console.log('done');});`
and for New York, it's -2 difference
`upsert('New York',myTempUpdate,-2).then(()=>{console.log('done');});`
so that the extra parameter gets sent through to the callback within `upsert()`.

Alternatively, maybe `update()` could be modified to do the same thing, using some sort of parameter data type checking.

**Comment by jakearchibald** [comment]
Thanks! I don't think this requires a feature in _this_ library, as it can be done with a general utility function.

```js
function appendCallbackArgs(callback, ...extraArgs) {
  return (...args) => callback(...args, ...extraArgs);
}

function callback(...args) {
  console.log(...args);
}

// Logs 'foo'
callback("foo");

const enhancedCallback = appendCallbackArgs(callback, "bar");

// Logs 'foo', 'bar'
enhancedCallback("foo");
```

For your particular example:

```js
const myTempUpdate = (v, vDelta) => (v || 0) + (vDelta || 1);

await update("Chicago", appendCallbackArgs(myTempUpdate, 3));
await update("New York", appendCallbackArgs(myTempUpdate, -2));
```

**Comment by compmeist** [comment]
Excellent, thank you much.   (Perhaps this is a useful snippet for the  `update()` documentation).

**Pull request closed without merging**
