### PR TITLE
Fix: allow values() method to return typed array

### PR DESCRIPTION
**Pull request by y-nk**
All is in the title.

### CODE REVIEW

**Comment by jakearchibald** [comment]
But… it doesn't return a typed array. I think maybe you _do_ need more than just the title here 😄

**Comment by y-nk** [comment]
@jakearchibald better 😅 ?

**Comment by jakearchibald** [comment]
Ohh, I thought you were talking about https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays.

Ok, I see what you mean now, but it seems weird to just do it for one method and not the others. Could you do it for the others too?

**Comment by y-nk** [comment]
@jakearchibald I couldn't find any other methods which needed extra typing 👌

**Comment by jakearchibald** [comment]
I haven't forgotten about this btw. I'm going to write some tests for it & land it.

**Comment by jakearchibald** [comment]
Released as 5.0.6. Thank you for the PR @y-nk!

**Comment by y-nk** [comment]
happy to be of help 🙏

**Pull request merged**
